### ISSUE TITLE
Debugging / Logging Does not work.

### ISSUE THREAD

**Issue by SamuelAsherRivello** [CapsCollective/raylib-cpp-starter#22]
The template is great. Its easy to get the project up and running.

However, there is no logging. Please add logging.

If I add logging to the `main.cpp` file

```
#include <iostream>
```

and

```
std::cout << "Hello World!" << std::endl;
```

There is no logging output to the terminal. See attached.

![image](https://github.com/user-attachments/assets/56b1c1f1-4c82-47b3-bd28-8fa27e7e1d8f)

**Comment by jonjondev** [comment]
Closing this issue now with the merge of the #26.
